### PR TITLE
Use untagged JSON encoding for single-constructor types

### PR DESCRIPTION
**Pull request by despresc**
This changes all of the single constructor `Table` types' `ToJSON` and `FromJSON` instances to the `Generic` ones, which has the effect of encoding them as arrays (for multi-argument constructors) or as the representation of the inner type (for `newtype` constructors).

All the other `newtype`-defined types in `Definition` have this encoding. The only other single constructor types in `Definition` are `Citation` (which is a record, and encoded as a JSON object) and `Pandoc` itself (which is encoded like a record, with additional metadata).

Closes: #75

### CODE REVIEW

**Comment by despresc** [comment]
Well, the multi-argument constructors are the `Generic` instance. The `newtype` constructors have the `GeneralizedNewtypeDeriving` instance, but the effect is the same.

**Comment by despresc** [comment]
Incidentally, `Meta` doesn't use the `newtype`-derived instances, and `Citation` doesn't use the `Generic` instances, when both give the same encoding as now. I'm not sure if you'd prefer explicit instances for the `Table` types, or if `Meta` and `Citation` should be changed to use the derived instances.

**Comment by jgm** [comment]
Great. It would be worth adding some testEncodeDecode test cases (in test-pandoc-citeproc.hs) to cover these.
In the past we've had at least one case where a derived encoding changed due to changes in dependencies, and this would at least catch such thing.s

**Comment by despresc** [comment]
That should be it. I've also found a small issue with the table model that is assumed in `Builder` that makes the table normalization in `Builder.table` a little too restrictive. I'll open a pull request soon, since that fix should probably be in the next version too (if you agree).

**Comment by despresc** [comment]
I'm not sure if this is welcome, but the template haskell instances should be at least as efficient as what is there now. They are probably more efficient for `ToJSON`, since they automatically give the instances a definition of `toEncoding`. This should fix the `Map` determinism issues as well, if the `Attr` serialization format is to be changed from a list of pairs to an object.

Otherwise I can remove that most recent commit.

**Comment by despresc** [comment]
The only thing that changed is that the keys for `Citation` now appear in the order in which they were defined, when serialized.

**Comment by jgm** [comment]
I'm on board for using TH (simpler maintenance), I think.  I know that earlier (236e80120fb15d70584259843879e923743b3a54) we created the manual instances instead of deriving them, because changes in the dependencies affected the generated JSON.  It is important that the JSON format be stable and fixed.  But given the number of base versions we're testing with, this seems pretty solid.

**Comment by jgm** [comment]
Note:  I've added this to master, bumped version to 1.22 (because of the JSON encoding changes, which could definitely be breaking for some users), and updated the changelog.  I'm thinking this should be released now, before we worry about the larger changes.  Does that seem right?

**Comment by despresc** [comment]
That seems reasonable, though I'm not too familiar with the normal tempo of `pandoc-types` releases. It could be good to get that change out now, since it might take a while to discuss the other changes?

**Comment by hadley** [comment]
This change seems to have had a fairly profound impact on the json AST, but I'm having a hard time figuring exactly what's changed because it's all explained in terms of Haskell types (which I'm not very familiar with). For my particular case, I _think_ it's that the children of `Table` no longer have `c` children, but their children are instead directly embedded? Does that sound plausible?

**Comment by despresc** [comment]
That sounds right. All of the table components with no variants are now represented by whatever their `"c"` content was, since the `"t"` type tag is unnecessary for them. In particular, these components changed: the table caption, table head, table bodies, table foot, row head column number, column and row span numbers, rows, and cells.

The keys in citation objects also have a slightly different order now, which is less important.

**Pull request merged**
