### PR TITLE
Implement shrink for Inlines and Blocks

### PR DESCRIPTION
**Pull request by link2xt**
Only caption is shrinked in tables for now.

### CODE REVIEW

**Comment by link2xt** [comment]
Just for example, it turns this
```
DefinitionList [([Str "x\8881/!",Space,Space],[[LineBlock [[Str "]3\9374\3815",Str "xu\6146[1q"]],Header 1 ("",[],[]) [Str "",Str ".(",RawInline (Format "html") "<a id=\"eek\">"],Div ("loc",[],[("start","22")]) [Para [Code ("",["haskell"],[]) "Qw|c"],Plain [Str "gKHR\7381[e"]]],[Plain [Code ("",["c","numberLines"],[]) "Po\7186"],BlockQuote [Plain [Str "\1320VA_|m"],LineBlock [[Link ("loc",["haskell"],[]) [Str "6)",Space,Space,Str "\DELA,m$bs",LineBreak,Space] ("L\\Vvi","Y2CRe'"),LineBreak,Str ",oT",Space]],LineBlock [[Emph [LineBreak],Emph [Str "0t+Spp\5136\3144",Str "Ix\DELu("],Link ("loc",[],[("a","11"),("b_2","a b c")]) [Str "\2239|\"/",Str "\5509 B]\""] ("x%F]\722!%","")]]],BulletList [[HorizontalRule],[CodeBlock ("",[],[]) "UR8uIJ"]]],[BlockQuote [CodeBlock ("",["c","numberLines"],[("a","11"),("b_2","a b c")]) "Nc",CodeBlock ("",["c","numberLines"],[("a","11"),("b_2","a b c")]) "7l",CodeBlock ("",[],[("start","22")]) "C;|%\8072"]]]),([Str "2\4735$A",Str "c|:p",SoftBreak,Str "{#"],[[Div ("loc",["c","numberLines"],[("a","11"),("b_2","a b c")]) [Para [Str "<O{M\597]{",RawInline (Format "html") "<a id=\"eek\">",Str "\5963a'#nG0A",Space],Para [LineBreak,LineBreak,Space,LineBreak,Space],Para [Str "p\7286]jO}"]]],[CodeBlock ("",["haskell"],[("a","11"),("b_2","a b c")]) "*C",BlockQuote [Para [Code ("",[],[("a","11"),("b_2","a b c")]) "ZJ3\DEL$"]]]])]
```
into this
```
DefinitionList [([],[[BlockQuote [LineBlock [[Link ("",[],[]) [Str "|",Str " ]"] ("","")]]]]])]
```
(made it by introducing artifical error and replaying with `--quickcheck-replay`).

**Comment by link2xt** [comment]
It also makes sense to flatten the lists, e.g by removing emphasis or replacing lists that have one list item with the list item contents, but it is already good enough at this point.

**Comment by jgm** [comment]
Looks good. Does adding 'shrink' require a new lower bound for QuickCheck?

**Comment by link2xt** [comment]
> Does adding 'shrink' require a new lower bound for QuickCheck?

No, it was present since the beginning of QuickCheck 2: https://hackage.haskell.org/package/QuickCheck-2.1.0.1/docs/Test-QuickCheck-Arbitrary.html

**Pull request merged**
